<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ArticleRequest extends FormRequest
{

	protected $dontFlash = ['files'];

	public function attributes()
	{
		return parent::attributes(); // TODO: Change the autogenerated stub
		/* return [
			'title' => '제목',
			'content' => '본문',
		]; */
	}

	/**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        //return false;
		return true;
    }

    public function messages()
	{
		return parent::messages(); // TODO: Change the autogenerated stub
		/* return [
			'required' => ':attribute은(는) 필수 입력 항목입니다.',
			'min' => ':attribute은(는) 최소 :min 글자 이상이 필요합니다.',
		]; */
	}

	/**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
			'content' => ['required', 'min:10'],
			'files' => ['array'],
			'files.*' => ['mimes:jpg,png,tar,txt,zip', 'max:30000'],
			'tags' => ['required', 'array'],
			'title' => ['required'],
        ];
    }
}
